const Data = [
  {
    img: `food/jollof.jpg`,
    rating: '4.8 (32)',
    time: `20-30 mins`,
    food: `Jollof Rice`,
    extra: `Rice, Chicken`,
    location: `6391 Elgin St. Celina`,
    reviewerIMG: `/food/woman.jpg`,
    review: `The jollof was rich and flavorful — felt just like home! Definitely ordering again.`,
    reviewer: `Sarah O.`,
  },
  {
    img: `food/plates.jpg`,
    rating: '4.9 (41)',
    time: `25-35 mins`,
    food: `Lamb Stew`,
    extra: `Rice & Dried fruits`,
    location: `6391 Elgin St. Celina`,
    reviewerIMG: `/food/man.jpg`,
    review: `Tender meat, amazing aroma, and perfect spice balance. 10/10!`,
    reviewer: `Michael D.`,
  },
  {
    img: `food/rice.jpg`,
    rating: '4.7 (29)',
    time: `20-25 mins`,
    food: `Vegetable Stew`,
    extra: `Rice & Sausage`,
    location: `6391 Elgin St. Celina`,
    reviewerIMG: `/food/youngWoman.jpg`,
    review: `Loved every bite — fresh veggies and tasty sausage combo!`,
    reviewer: `Ada N.`,
  },
  {
    img: `food/riceBeaf.jpg`,
    rating: '4.8 (36)',
    time: `20-30 mins`,
    food: `Meat Stew Lamb`,
    extra: `Dried fruits & Rice`,
    location: `6391 Elgin St. Celina`,
    review: `Juicy lamb and rich sauce — perfectly cooked!`,
    reviewer: `Daniel K.`,
  },
  {
    img: `food/spaghetti.jpg`,
    rating: '4.9 (40)',
    time: `15-25 mins`,
    food: `Oven Baked Pasta`,
    extra: `Spaghetti`,
    location: `6391 Elgin St. Celina`,
    review: `So creamy and cheesy! My favorite comfort food on the menu.`,
    reviewer: `Blessing A.`,
  },
  {
    img: `food/plantain.jpg`,
    rating: '5.0 (52)',
    time: `20-25 mins`,
    food: `Rice & Plantain`,
    extra: `Meat Sauce`,
    location: `6391 Elgin St. Celina`,
    review: `Crispy plantain, tender meat — everything was on point.`,
    reviewer: `Emeka O.`,
  },
  {
    img: `food/soup.jpg`,
    rating: '4.9 (44)',
    time: `25-35 mins`,
    food: `Black Soup`,
    extra: `Semo`,
    location: `6391 Elgin St. Celina`,
    review: `Authentic Nigerian black soup flavor. Tastes like grandma’s recipe.`,
    reviewer: `Amara T.`,
  },
]

export default Data
